### ISSUE TITLE
www. redirection

### ISSUE THREAD

**Issue by ewerybody** [rhein-main-swingtime/rmswing.de#1]
Currently people remembering the golden age of Internetz didn't die of age yet so it might happen someone tries to goto www.rmswing.de which fails.

I'd strongly suggest to actually **redirect** to [rmswing.de](rmswing.de) so the resulting links never appear with a www. and when people copy links there are no 2 versions of the same address.

can we do that?

**Comment by mafeka** [comment]
Yes, we can!

**Comment by mafeka** [comment]
Solved via .htaccess
