### ISSUE TITLE
Automatic deployments

### ISSUE THREAD

**Issue by mafeka** [rhein-main-swingtime/rmswing.de#3]
We're lazy buggers, because of that we don't want to bother with manually uploading files somewhere. Instead we'd rather have our fancy little page automatically deployed after a push/merge into a specific git branch, like this:

- Pullrequest get's merged into branch
- Github Webhook triggers action on server
- Server clones repo, moves it into place, updates/sync submodule (specific plugins and/or themes)
- Everybody is happy and goes for a beer and a dance.

**Comment by mafeka** [comment]
Works :)

Some improvements could be made, but for now I'm happy.

**Comment by ewerybody** [comment]
I got mail! :D

**Comment by mafeka** [comment]
Yeah :)

Eric Werner <notifications@github.com> schrieb am Di. 12. Feb. 2019 um
20:14:
